version: "3.9"


services:
  bucket-service:
    container_name: bucket-service
    build:
      context: bucket-service/.
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - ujin-backend
    ports:
      - "8001:8001"
    env_file:
      - .env

  app-service:
    container_name: app-service
    build:
      context: app/.
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - ujin-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
networks:
  ujin-backend:
    driver: bridge