version: "3.9"

include:
  - path: front/docker-compose.yaml

services:
  bucket-service:
    container_name: bucket-service
    build:
      context: bucket-service/.
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - ujin-backend
    ports:
      - "8000"
    environment:
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - ENDPOINT_URL=${ENDPOINT_URL}
      - BUCKET_NAME=${BUCKET_NAME}



  app-service:
    container_name: app-service
    build:
      context: app/.
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - ujin-backend
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - bucket-service
      - mongodb-service
    links:
      - mongodb-service
      - bucket-service

  gateway-service:
    container_name: gateway-service
    build:
      context: gateway/.
      dockerfile: Dockerfile
    networks:
      - ujin-backend
    ports:
      - "8080:8080"
    depends_on:
      - app-service
    links:
      - app-service

  mongodb-service:
    container_name: mongodb-service
    image: mongo
    networks:
      - ujin-backend
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db


networks:
  ujin-backend:
    driver: bridge

volumes:
  dbdata6: