version: "3.9"


services:
  bucket-service:
    container_name: bucket-service
    build:
      context: bucket-service/.
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - ujin-backend
    ports:
      - "8000"
    env_file:
      - .env

  app-service:
    container_name: app-service
    build:
      context: app/.
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - ujin-backend
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - bucket-service

  gateway-service:
    container_name: gateway-service
    build:
      context: gateway/.
      dockerfile: Dockerfile
    networks:
      - ujin-backend
    ports:
      - "8080:8080"
    depends_on:
      - app-service


networks:
  ujin-backend:
    driver: bridge