version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: ujin-nginx
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - ujin-backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./build:/etc/nginx/www

networks:
  ujin-backend:
    driver: bridge